id: P0A4DBC4E
initial_creation_type: input
source_metadata:
  title: Yeshe Dorje
  language: bo
  description: 'Texts by and about Yeshe Dorje (ye shes rdo rje), a prominent disciple
    of Nyala Pema Düdul who stayed at Lumorab monastery for many years along with
    Tertön Rangrik Dorje:'
  volume:
    8098d10530a040d9949d47a6959df199:
      title: Prayer to the Lineage of Lumorab
      parent: Lineage Prayers
created_at: '2022-03-01T02:02:12.021668'
last_modified_at: '2022-03-01T02:02:12.021671'
statistics:
  total_words: 865
  total_non_words: 61
quality:
  non_words_ratio: 0.07
